repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/willthames/ansible-lint.git
  sha: v3.4.11
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
